<a href="https://colab.research.google.com/github/ttma333/python/blob/main/sql_%EB%A6%AC%EC%8A%A4%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pwd

'/content'

In [2]:
cd/content/drive/MyDrive/SQL/mappers

/content/drive/MyDrive/SQL/mappers

In [3]:
import pandas as pd

In [4]:
import os
list = ['interest','job','map','member','video']
for i in list:
  path = f'/content/drive/MyDrive/SQL/mappers/{i}'
  file_list = os.listdir(path)
  abc = globals()[f'file_list_{i}'] = [file for file in file_list if file.endswith('.xml')] 
  for j,p in zip(abc,range(1,len(abc)+1)):
    basename = os.path.basename(f'{i}/{j}')
    name ,ext = os.path.splitext(basename)
    globals()[f'_{p}_{i}_{name}'] = pd.read_xml(f'{i}/{j}')

In [5]:
_1_member_MemberMapper

,id,parameterType,resultType,select,insert,update,delete
0,loginCheck,string,string,SELECT memPw FROM member WHERE memId = #{memId},None,None,None
1,insertMember,com.jobdongsan.project.model.MemberVO,None,None,"INSERT INTO member (memId, memPw, memName, mem...",None,None
2,insertOauthMember,com.jobdongsan.project.model.MemberVO,None,None,"INSERT INTO member (memId, memPw, memName, mem...",None,None
3,checkMemId,String,String,SELECT memId FROM member WHERE memId = #{memId},None,None,None
4,getMemberInfo,String,com.jobdongsan.project.model.MemberVO,SELECT * FROM member WHERE memId = #{memId},None,None,None
5,mypageCheck,String,String,SELECT memPw FROM member WHERE memId = #{memId},None,None,None
6,checkMemEmail,String,String,SELECT memEmail FROM member WHERE memEmail = #...,None,None,None
7,findMemId,String,com.jobdongsan.project.model.MemberVO,SELECT * FROM member WHERE memEmail = #{memEmail},None,None,None
8,updateMemPw,HashMap,None,None,None,UPDATE member SET memPw = #{newPw} where memId...,None
9,updateMemberInfo,com.jobdongsan.project.model.MemberVO,None,None,None,"UPDATE member SET memPw = #{memPw}, memName = ...",None
10,checkMemInfo,HashMap,String,SELECT memPw FROM member WHERE memId = #{memId...,None,None,None
11,deleteMember,String,None,None,None,None,DELETE FROM member WHERE memId = #{memId}
12,findByProviderAndProviderId,HashMap,com.jobdongsan.project.model.MemberVO,SELECT * FROM member WHERE provider = #{provid...,None,None,None